### ISSUE TITLE
smbprotocol.exceptions.BufferOverflow: <exception str() failed>

### ISSUE THREAD

**Issue by witar123** [SomePersonOk/ChromeCookieStealer#3]
**It gives me this error**

Traceback (most recent call last):
  File "C:\Users\witar1\Downloads\cookie.py", line 168, in <module>
    get_cookies()
  File "C:\Users\witar1\Downloads\cookie.py", line 136, in get_cookies
    v20_key = retrieve_v20_key()
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\witar1\Downloads\cookie.py", line 74, in retrieve_v20_key
    encrypted_key_b64, stderr, rc = client.run_executable(
                                    ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\witar1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pypsexec\client.py", line 433, in run_executable
    exe_result_raw = main_pipe.read(0, 1024)
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\witar1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\smbprotocol\open.py", line 1256, in read
    return self._read_response(request, wait)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\witar1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\smbprotocol\open.py", line 1264, in _read_response
    response = self.connection.receive(request, wait=wait)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\witar1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\smbprotocol\connection.py", line 1103, in receive
    raise SMBResponseException(response)
smbprotocol.exceptions.BufferOverflow: <exception str() failed>

**Comment by EduContin** [comment]
Instead of using Python to run that separated program, leverage the Windows Built-in DPAPI API via Powershell.

I'm going to push a PR soon with the fix
